FROM ubuntu:16.04
MAINTAINER TRAN Hoang Tung <tran-hoang.tung@usth.edu.vn>

# OpenCV install script:
# https://github.com/milq/milq/blob/master/scripts/bash/install-opencv.sh
# Nice Dockerfile format:
# https://github.com/victorhcm/dockerfiles/blob/master/opencv/Dockerfile

WORKDIR /root
