FROM resin/rpi-raspbian:stretch
MAINTAINER TRAN Hoang Tung <tran-hoang.tung@usth.edu.vn>

WORKDIR /root

RUN [ "cross-build-start" ]

# Install dependencies
RUN apt-get update

RUN [ "cross-build-end" ]  
